input               :  "/core/projects/EBP/conservation/gen_assembly_pipeline/hoolock_chrm_3/samplesheet.csv"
outdir                 :  "chrm_3_ont+pb+ill_ehg_output"
fastq                  :  "/core/projects/EBP/conservation/gen_assembly_pipeline/hoolock_chrm_3/chr3_ont.fastq.gz"
centrifuge_db          :  "/core/labs/Wegrzyn/IngaGenome/Contam/longReads/f+b+a+v/"
busco_lineage          :  "primates_odb10"
kraken_db              :  "/isg/shared/databases/kraken2/microDB"
rcf_db                 :  "/isg/shared/databases/recentrifuge/taxdump/"
ragtag_reference       :  "/core/projects/EBP/conservation/gen_assembly_pipeline/hoolock_chrm_3/polished_chr3.fasta"
taxon_taxid            : "593543"
taxon_taxdump          : "/core/projects/EBP/conservation/gen_assembly_pipeline/nextflow_dev/ncbi_taxdump"
blast_db               : "/isg/shared/databases/blast/v5/nt"
