input                  :  "/core/projects/EBP/conservation/gen_assembly_pipeline/nextflow_dev/samplesheet_test.csv"
outdir                 :  "test_outdir_9_191sr"
fastq                  :  "/core/projects/EBP/conservation/zigzag_coral/191/long_read/01_raw_reads/Mo_191_p1s.fastq"
centrifuge_db          :  "/core/labs/Wegrzyn/IngaGenome/Contam/longReads/f+b+a+v/"
busco_lineage          :  "metazoa_odb10"
summary_txt            :  "/archive/projects/EBP/roneill/reads/nanopore/promethion/DOG/Madrepora/Mo_S0424_FK21-191/2023JAN17_DOG_Mo_S0424_FK21-191_PAM25097/2023JAN17_DOG_Mo_S0424_FK21-191_PAM25097/20230117_2211_1C_PAM25097_ab58fe1c/sequencing_summary_PAM25097_ab58fe1c_a47ef4ef.txt"
kraken_db              :  "/isg/shared/databases/kraken2/microDB"
rcf_db                 :  "/isg/shared/databases/recentrifuge/taxdump/"
model                  :  "r1041_e82_400bps_sup_g615"
ragtag_reference       :  "/core/projects/EBP/conservation/zigzag_coral/212/long_read/03_assembly/flye/p1si_filtered/assembly.fasta"
manual_genome_size     :  "866000000"
masurca_config         :  "/core/projects/EBP/conservation/gen_assembly_pipeline/nextflow_dev/masurca_sr_config_file"
taxon_taxid            : "2488345"
taxon_taxdump          : "/core/projects/EBP/conservation/gen_assembly_pipeline/nextflow_dev/ncbi_taxdump"
blast_db               : "/isg/shared/databases/blast/v5/nt"
flye_mode              : "both"
